apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-watch
  labels:
    component: kube-watch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: kube-watch
    spec:
      containers:
      - name: kube-watch
        image: drgarcia1986/kube-watch:0.0.1
        imagePullPolicy: Always
        env:
        - name: K8SENV
          value: <your-k8s-environment-label>
        - name: CIRCLETIME
          value: "5"
        - name: SLACKAVATAR
          value: <slack-avatar-for-bot>
        - name: SLACKCHANNEL
          value: <slack-channel>
        - name: SLACKTOKEN
          valueFrom:
            secretKeyRef:
              name: kube-watch
              key: token
